import { Comfortaa } from "next/font/google";
import "../globals.css";

const comfortaa = Comfortaa({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <html lang="en" className={`${comfortaa.className} antialiased h-full`}>
      <body className="min-h-full flex flex-col bg-[#FDF8F6]">
        {children}
      </body>
    </html>
  );
}
