import { Comfortaa } from "next/font/google";
import "../globals.css";
import ToasterProvider from "@/components/ToasterProvider";

const comfortaa = Comfortaa({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${comfortaa.className} antialiased h-full`}>
      <body className="min-h-full flex flex-col bg-[#FDF8F6] overflow-x-hidden">
        {children}
        <ToasterProvider />
      </body>
    </html>
  );
}
