import { Toaster } from 'react-hot-toast';
import { Comfortaa } from "next/font/google";
import "../globals.css";
import ProfileMenu from "@/components/profileMenu";
import ToasterProvider from "@/components/ToasterProvider";


const comfortaa = Comfortaa({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${comfortaa.className} antialiased h-full`}>
      <body className="min-h-full bg-[#FDF8F6] grid grid-cols-10 overflow-hidden">
        <ProfileMenu />
        {children}
        <ToasterProvider/>
      </body>
    </html>
  );
}
